import "./globals.css";

import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "@/providers";
import { cn } from "@nextui-org/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1
}

interface RootLayoutProps {
  children: React.ReactNode
}

const bodyClasses = cn(
  geistSans.variable,
  geistMono.variable,
  "antialiased flex min-h-[100dvh] flex-col overflow-auto bg-default-50",
  "scroll-smooth scrollbar-thumb-active-default-400 scrollbar-thumb-default-200 scrollbar-thumb-hover-default-300 scrollbar-track-default-50"
);

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={bodyClasses}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
