name: Deploy Web to Vercel

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'config/**'
      - 'packages/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
            version: 8.9.0

      - uses: actions/setup-node@v4
        with:
            node-version: 22
            registry-url: https://registry.npmjs.org
            cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build web
        run: pnpm --filter web build

      - name: Deploy to Vercel (Web)
        run: |
          npx vercel --cwd apps/web --prod --confirm \
            --token ${{ secrets.VERCEL_TOKEN }} \
            --org ${{ secrets.VERCEL_ORG_ID_WEB }} \
            --project ${{ secrets.VERCEL_PROJECT_ID_WEB }}
